(package "emoji-github"
         "0.2.3"
         "Display list of GitHub's emoji.  (cheat sheet)")

(website-url "https://github.com/jcs-elpa/emoji-github")
(keywords "convenience" "list" "github" "emoji" "display")

(package-file "emoji-github.el")

(source "melpa")

(depends-on "emacs" "24.4")
(depends-on "emojify")
(depends-on "request")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
